image: alpine:latest

include:
  - project: 'cloudnua-public/gitops/infra/templates'
    ref: main
    file:
      - '/terraform.gitlab-ci.yml'

# Using protected pipeline variable for initial deployment
variables:
  AZURE_ID: $ARM_CLIENT_ID
  AZURE_SECRET: $ARM_CLIENT_SECRET
  AZURE_SUB_ID: $ARM_SUBSCRIPTION_ID
  AZURE_TEN_ID: $ARM_TENANT_ID
  GITLAB_TOKEN: $GITLAB_TOKEN

# Using protected pipeline variable for initial deployment
before_script:
  - echo "Initialise AZURE AKS Stack...START!"

  - export ARM_CLIENT_ID=echo $AZURE_ID | base64 -d
  - export ARM_CLIENT_SECRET=echo $AZURE_SECRET | base64 -d
  - export ARM_SUBSCRIPTION_ID=echo $AZURE_SUB_ID | base64 -d
  - export ARM_TENANT_ID=echo $AZURE_TEN_ID | base64 -d

after_script:
  - echo ""Initialise AZURE AKS Stack...DONE!""